### ISSUE TITLE
The URL changes with every new version

### ISSUE THREAD

**Issue by ikarisan** [mc51/Corona-Test-Comparison#1]
Hi!

Thank you for this good work!
But the hard coded URL seems to change with every new version. You used
https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/evaluierung-sensitivitaet-sars-cov-2-antigentests.pdf?__blob=publicationFile&v=71
but since last monday (31. Jan. 2022) the version at the end changed to 77 (?v=77)

Maybe an URL without the version parameter will always deliver the latest version:

https://www.pei.de/SharedDocs/Downloads/DE/newsroom/dossiers/evaluierung-sensitivitaet-sars-cov-2-antigentests.pdf?__blob=publicationFile

**Comment by mc51** [comment]
Hi @ikarisan,

Thanks for the feedback. I appreciate it. It seems that the version number in the url does not have any effect. The downloaded file will always be the same. However, I've [removed the version](https://github.com/mc51/Corona-Test-Comparison/commit/6344a0ae7085ca10573f73b37f97dcc74be04f70) parameter from the query, because it is not needed.

Also, I missed that there was an update of the data. Thanks for the hint! Now, I've configured my server to check for new data daily and use it when available. Hopefully, that will work.
